# Generated by Django 2.0.5 on 2018-10-29 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8528d5f5-3bee-34b3-b2a0-2a1f262465f4'), max_length=64),
        ),
    ]
