# Generated by Django 2.0.5 on 2018-11-21 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d625abca-ffa6-3d91-9afb-679437bdc27e'), max_length=64, unique=True),
        ),
    ]
