# Generated by Django 2.0.5 on 2018-10-30 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181029_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_mode',
            name='department_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='部门管理员'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('9eb46fa6-3364-3304-ae02-bc8764084d13'), max_length=64),
        ),
    ]
