# Generated by Django 2.0.5 on 2018-10-30 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181030_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default=uuid.UUID('36535bee-62b2-3eb5-bb9d-ea3bc2d393f6'), max_length=64),
        ),
    ]
