# Generated by Django 2.0.5 on 2018-11-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('describe', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'ansible主机组',
                'verbose_name_plural': 'ansible主机组',
            },
        ),
    ]
