# Generated by Django 2.0.5 on 2018-10-26 08:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ansible_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('content', models.TextField(null=True, verbose_name='修改详情')),
            ],
            options={
                'verbose_name_plural': '资产日志',
                'verbose_name': '资产日志',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='机房名称')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'IDC机房'), (1, '公有云'), (2, '私有云')], null=True, verbose_name='机房类型')),
                ('address', models.CharField(max_length=20, verbose_name='机房位置')),
                ('contack_name', models.CharField(max_length=10, verbose_name='联系人')),
                ('contack_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('contack_qq', models.CharField(blank=True, max_length=10, null=True, verbose_name='联系qq')),
                ('contack_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('bandwidth', models.CharField(blank=True, max_length=10, null=True, verbose_name='机房带宽')),
            ],
            options={
                'verbose_name_plural': 'IDC列表',
                'verbose_name': 'IDC列表',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '服务标签',
                'verbose_name': '服务标签',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '业务组',
                'verbose_name': '业务组名称',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用状态')),
                ('system', models.IntegerField(choices=[(0, 'CentOS 5'), (1, 'CentOS 6'), (2, 'CentOS 7'), (3, 'Ubuntu 16'), (4, 'Ubuntu 15'), (5, 'Windows 2012'), (6, 'Windows 2008')], verbose_name='操作系统')),
                ('location', models.CharField(blank=True, max_length=30, null=True, verbose_name='机架位置')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('ssh_user', models.CharField(default='root', max_length=20, verbose_name='连接用户名')),
                ('manufacturer', models.CharField(blank=True, max_length=20, verbose_name='厂商')),
                ('productname', models.CharField(blank=True, max_length=30, verbose_name='产品型号')),
                ('service_tag', models.CharField(blank=True, max_length=80, null=True, verbose_name='序列号')),
                ('cpu_model', models.CharField(blank=True, max_length=50, verbose_name='CPU型号')),
                ('cpu_nums', models.CharField(blank=True, max_length=50, verbose_name='CPU线程数')),
                ('cpu_groups', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU物理核数')),
                ('mem', models.CharField(blank=True, max_length=100, verbose_name='内存大小')),
                ('disk', models.CharField(blank=True, max_length=300, verbose_name='硬盘大小')),
                ('hostname', models.CharField(blank=True, max_length=30, verbose_name='主机名')),
                ('ip2', models.CharField(blank=True, max_length=50, null=True, verbose_name='其他IP地址')),
                ('ansible_group', models.ManyToManyField(blank=True, to='ansible_api.AnsibleServerGroup', verbose_name='ansible组')),
                ('idc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='所属机房')),
                ('label', models.ManyToManyField(blank=True, to='assets.Label', verbose_name='服务标签')),
                ('project', models.ManyToManyField(blank=True, to='assets.Project', verbose_name='业务组')),
            ],
            options={
                'verbose_name_plural': '主机列表',
                'verbose_name': '主机列表',
            },
        ),
        migrations.AddField(
            model_name='assetoperationlog',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Server', verbose_name='主机ID'),
        ),
    ]
