# Generated by Django 2.0.5 on 2018-11-21 07:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_group',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='角色名称')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('explanation', models.TextField(verbose_name='角色描述')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '角色管理',
                'verbose_name_plural': '角色管理',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupNode',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
                'verbose_name': '部门权限',
                'db_table': 'AuthGroupNode',
                'verbose_name_plural': '部门权限',
            },
        ),
        migrations.CreateModel(
            name='AuthNode',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authnode_node', to='assets.Server', to_field='uuid', verbose_name='主机')),
            ],
            options={
                'managed': True,
                'verbose_name': '主机权限',
                'db_table': 'AuthNode',
                'verbose_name_plural': '主机权限',
            },
        ),
        migrations.CreateModel(
            name='AuthSudo',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('groupname', models.CharField(help_text='sudo组', max_length=64, verbose_name='组名')),
                ('shell', models.TextField(verbose_name='命令')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'sudo授权',
                'db_table': 'AuthSudo',
                'verbose_name_plural': 'sudo授权',
            },
        ),
        migrations.CreateModel(
            name='user_auth_cmdb',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('select_host', models.BooleanField(default=False, verbose_name='查看资产')),
                ('edit_host', models.BooleanField(default=False, verbose_name='修改资产')),
                ('update_host', models.BooleanField(default=False, verbose_name='更新资产')),
                ('add_host', models.BooleanField(default=False, verbose_name='添加主机')),
                ('bat_add_host', models.BooleanField(default=False, verbose_name='批量添加')),
                ('delete_host', models.BooleanField(default=False, verbose_name='删除资产')),
                ('idc_list', models.BooleanField(default=False, verbose_name='查看IDC')),
                ('idc_add', models.BooleanField(default=False, verbose_name='添加IDC')),
                ('idc_del', models.BooleanField(default=False, verbose_name='删除IDC')),
                ('idc_edit', models.BooleanField(default=False, verbose_name='修改IDC')),
                ('project_list', models.BooleanField(default=False, verbose_name='查看项目组')),
                ('project_add', models.BooleanField(default=False, verbose_name='添加项目组')),
                ('project_edit', models.BooleanField(default=False, verbose_name='修改项目组')),
                ('project_del', models.BooleanField(default=False, verbose_name='删除项目组')),
                ('label_list', models.BooleanField(default=False, verbose_name='查看标签组')),
                ('label_add', models.BooleanField(default=False, verbose_name='添加标签组')),
                ('label_edit', models.BooleanField(default=False, verbose_name='修改标签组')),
                ('label_del', models.BooleanField(default=False, verbose_name='删除标签组')),
                ('user_list', models.BooleanField(default=False, verbose_name='用户管理')),
                ('user_edit', models.BooleanField(default=False, verbose_name='修改用户')),
                ('user_del', models.BooleanField(default=False, verbose_name='删除用户')),
                ('user_active', models.BooleanField(default=False, verbose_name='禁用用户')),
                ('department_list', models.BooleanField(default=False, verbose_name='部门管理')),
                ('department_add', models.BooleanField(default=False, verbose_name='添加部门')),
                ('department_edit', models.BooleanField(default=False, verbose_name='修改部门')),
                ('department_del', models.BooleanField(default=False, verbose_name='删除部门')),
                ('exec_cmd', models.BooleanField(default=False, verbose_name='执行命令')),
                ('update_file', models.BooleanField(default=False, verbose_name='更新文件')),
                ('file_list', models.BooleanField(default=False, verbose_name='文件列表')),
                ('upload_file', models.BooleanField(default=False, verbose_name='上传文件')),
                ('group_name', models.ForeignKey(help_text='添加角色组权限', on_delete=django.db.models.deletion.CASCADE, related_name='user_auth_cmdb_auth_group', to='authorize.auth_group', verbose_name='所属角色')),
            ],
            options={
                'verbose_name': '权限管理',
                'verbose_name_plural': '权限管理',
            },
        ),
    ]
