# Generated by Django 2.0.5 on 2018-10-29 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_group',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='角色名称')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('explanation', models.TextField(verbose_name='角色描述')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('group_user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '角色管理',
                'verbose_name_plural': '角色管理',
            },
        ),
        migrations.CreateModel(
            name='AuthNode',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('auth', models.BooleanField(default=0, verbose_name='是否管理员')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Server', verbose_name='主机')),
                ('user_name', models.ForeignKey(help_text='用户', max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='名称')),
            ],
            options={
                'verbose_name': '主机权限',
                'managed': True,
                'db_table': 'AuthNode',
                'verbose_name_plural': '主机权限',
            },
        ),
        migrations.CreateModel(
            name='AuthSudo',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('groupname', models.CharField(help_text='sudo组', max_length=64, verbose_name='组名')),
                ('shell', models.TextField(verbose_name='命令')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sudo授权',
                'managed': True,
                'db_table': 'AuthSudo',
                'verbose_name_plural': 'sudo授权',
            },
        ),
        migrations.CreateModel(
            name='user_auth_cmdb',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('select_host', models.BooleanField(default=False, verbose_name='查看资产')),
                ('edit_host', models.BooleanField(default=False, verbose_name='修改资产')),
                ('update_host', models.BooleanField(default=False, verbose_name='更新资产')),
                ('add_host', models.BooleanField(default=False, verbose_name='添加主机')),
                ('bat_add_host', models.BooleanField(default=False, verbose_name='批量添加')),
                ('delete_host', models.BooleanField(default=False, verbose_name='删除资产')),
                ('add_line_auth', models.BooleanField(default=False, verbose_name='产品线管理')),
                ('auth_project', models.BooleanField(default=False, verbose_name='自动化发布')),
                ('auth_highstate', models.BooleanField(default=False, verbose_name='自动化部署')),
                ('add_user', models.BooleanField(default=False, verbose_name='添加用户')),
                ('edit_user', models.BooleanField(default=False, verbose_name='修改用户')),
                ('edit_pass', models.BooleanField(default=False, verbose_name='修改密码')),
                ('delete_user', models.BooleanField(default=False, verbose_name='删除用户')),
                ('add_department', models.BooleanField(default=False, verbose_name='部门管理')),
                ('select_idc', models.BooleanField(default=False, verbose_name='查看机房')),
                ('add_idc', models.BooleanField(default=False, verbose_name='添加机房')),
                ('edit_idc', models.BooleanField(default=False, verbose_name='修改机房')),
                ('del_idc', models.BooleanField(default=False, verbose_name='删除机房')),
                ('setup_system', models.BooleanField(default=False, verbose_name='安装系统')),
                ('upload_system', models.BooleanField(default=False, verbose_name='主机上报')),
                ('salt_keys', models.BooleanField(default=False, verbose_name='主机上报')),
                ('project_auth', models.BooleanField(default=False, verbose_name='项目列表')),
                ('add_project', models.BooleanField(default=False, verbose_name='添加项目')),
                ('edit_project', models.BooleanField(default=False, verbose_name='修改项目')),
                ('delete_project', models.BooleanField(default=False, verbose_name='删除项目')),
                ('auth_log', models.BooleanField(default=False, verbose_name='salt执行记录')),
                ('cmdb_log', models.BooleanField(default=False, verbose_name='资产操作记录')),
                ('server_audit', models.BooleanField(default=False, verbose_name='服务器操作记录')),
                ('group_name', models.ForeignKey(help_text='添加角色组权限', on_delete=django.db.models.deletion.CASCADE, to='authorize.auth_group', verbose_name='所属角色')),
            ],
            options={
                'verbose_name': '权限管理',
                'verbose_name_plural': '权限管理',
            },
        ),
    ]
